In [1]:
import numpy as np
import pandas as pd

In [2]:
import math

print(math.cos(math.pi/2))  # should be zero but has some value so avoid cos.pi/2==0 use if(cos(pi/2) <= 1E-15)
print(math.sin(math.pi/2))

6.123233995736766e-17
1.0


### Vector

In [13]:
vector = np.array([[4],[-1],[2]])
print (vector)
zero_vector=np.array([[0],[0],[0]])
print(zero_vector)
print(vector[0:2])
print(vector.T)
print(np.linalg.norm(vector))  # magnitude or normalization or magnitude from (0,0,0)

[[ 4]
 [-1]
 [ 2]]
[[0]
 [0]
 [0]]
[[ 4]
 [-1]]
[[ 4 -1  2]]
4.58257569495584


### Exercise 

In [5]:
v1 = np.array([[4],[-1],[2]])
v2 = np.array([[2],[4],[8]])
np.linalg.norm(v1-v2)   # Euclidean distance

8.06225774829855

### Matrix

In [3]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6,7],[8,9,10],[11,12,13]])
m2[1,1]

9

In [25]:
print(np.diag([1,2,3]))
print("\n")
print(np.identity(3))

#Symetric matrix = a = a.T

s1 = np.array([[2,3,1],[3,4,-1],[1,-1,1]])
print(s1)
print(s1.T)
print("\n")

#Triangular matrix

print(np.tril([[1,2,3],[4,5,6],[7,8,9]]))
print("\n")
print(np.tril([[1,2,3],[4,5,6],[7,8,9]],-1))
print("\n")
print(np.triu([[1,2,3],[4,5,6],[7,8,9]]))
print("\n")
print(np.triu([[1,2,3],[4,5,6],[7,8,9]],1))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
[[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]


[[1 0 0]
 [4 5 0]
 [7 8 9]]


[[0 0 0]
 [4 0 0]
 [7 8 0]]


[[1 2 3]
 [0 5 6]
 [0 0 9]]


[[0 2 3]
 [0 0 6]
 [0 0 0]]


### Operations on Vectors and Matrices

In [35]:
vector_1 = np.array([[21, -97, 35]]) 
vector_2 = np.array([[52, 48, -25]]) 
print(vector_1+vector_2)
print("\n")
matrix_1 = np.array([[21, -97, 35], [-86, 26, 70]]) 
matrix_2 = np.array([[52, 48, -25], [23, 6, 9]]) 
print(matrix_1+matrix_2)
print("\n")
print(6*vector_1)
print("\n")
print(6*matrix_1)
print("\n")

[[ 73 -49  10]]


[[ 73 -49  10]
 [-63  32  79]]


[[ 126 -582  210]]


[[ 126 -582  210]
 [-516  156  420]]




#### Inner Product

In [37]:
vector_1 = np.array([[21, -97, 35]]) 
vector_2 = np.array([[52, 48, -25]]) 
print(vector_1*vector_2)


[[ 1092 -4656  -875]]


##### Angle Between Vectors
###### cos(o) = (v1.T).v2/norm(v1).norm(v2)

In [200]:
def angle_between(v1, v2):
    a = np.dot(v1.T,v2)
    b = np.linalg.norm(v1)*np.linalg.norm(v2)
    return a/b

v1 = np.array([1,2,3])
v2 = np.array([1,0,3]) 
c = np.arccos(angle_between(v1,v2)) ## cosine inverse
print(np.rad2deg(c))
print("Angle Between Two Vector :",np.rad2deg(np.arccos(angle_between(v1,v2))))

32.31153323742385
Angle Between Two Vector : 32.31153323742385


#### Cauchy-Schwarz Inequality
###### Basically, if the inner product of the vectors is equal to the product of the norm of the vectors, the vectors are linearly dependent.
###### (v1.T).v2 <= ||v1||.||v2||
###### vector1 and vector2 in dependent if they are divisible of each other
###### The linearly dependent vectors are parallel to each other.

In [197]:
matrix_1 = np.array([3,-1,2]) 
matrix_2 = np.array([2,6,-1]) 
# print(np.abs(np.dot(matrix_1.T,matrix_2)))
# print(np.dot(np.linalg.norm(matrix_1), np.linalg.norm(matrix_2)))
if((np.abs(np.dot(matrix_1.T,matrix_2))) <= np.dot(np.linalg.norm(matrix_1), np.linalg.norm(matrix_2))):
  print("Dependent")
else:
  print("Independent")

def Cauchy_Schwarz(v1,v2):
    if((np.abs(np.dot(v1.T,v2))) <= np.dot(np.linalg.norm(v1), np.linalg.norm(v2))):
        print("Dependent")
    else:
        print("Independent")

Dependent


###### Exercise

In [198]:
v1 = np.array([[1],[1],[1]])
v2 = np.array([[2],[2],[2]])
Cauchy_Schwarz(v1,v2)
v3 = np.array([[1],[1],[1]])
v4 = np.array([[1],[3],[1]])
Cauchy_Schwarz(v3,v4)

Independent
Dependent


##### Matrix Vector Multiplication

In [201]:
Matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_vector = np.array([[1], [2], [3]])
# print(column_vector.shape)
product = np.matmul(Matrix_3x3,column_vector,)
print("Product: ", product)

Product:  [[14]
 [32]
 [50]]


##### Matrix Multiplication

In [204]:
import numpy as np
Matrix_3x3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
Matrix_4x3 = np.array([[4, 2, 3],[2, 0, 7],[-1, 6, -3],[1, 3, 0]])
result=np.dot(Matrix_3x3,Matrix_4x3.T)
print(result)

[[33 51  2 13]
 [42 60  4 17]
 [51 69  6 21]]


##### Permutation Matrix

In [207]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ide = np.array([[0,1,0],[1,0,0],[0,0,1]])
print(mat*ide)

[[0 2 0]
 [4 0 0]
 [0 0 9]]


#### Orthogonal Projection
###### Orthogonal projection of vector v1 on vector v2 is the point (p) on v2 which is closest to v1. 
###### p = ((v2.T).v1/(v2.T).v2).v2

In [210]:
vector_1 = np.array([2,3])
vector_2 = np.array([4,4]) 
orthogonal_projection1 = np.dot(np.true_divide(np.dot(vector_2.T,vector_1), np.dot(vector_2.T,vector_2)),vector_2)
orthogonal_projection2 = np.dot(np.dot(vector_2.T,vector_1)/np.dot(vector_2.T,vector_2),vector_2)
print(orthogonal_projection1)
print(orthogonal_projection2)

[2.5 2.5]
[2.5 2.5]


#### Determinants

In [211]:
matrix = np.array([ [[1, 2], [9, 4]], [[1, 2], [-8, 1]], [[1, 3], [3, 0]] ])
print(np.linalg.det(matrix))

[-14.  17.  -9.]


##### Exercise

In [219]:
m1 = np.array([[3,1,4],[-1,2,1],[2,3,1]])
print(np.linalg.det(m1))
m2 = np.array([[1,3,4],[2,-1,1],[3,2,1]])
print(np.linalg.det(m2))
m3 = np.array([[3,4,1],[-1,1,2],[2,1,3]])
print(np.linalg.det(m3))
m4 = np.array([[6,1,4],[-2,2,1],[4,3,1]])
print(np.linalg.det(m4))
m5 = np.array([[6,3,4],[-2,6,1],[4,9,1]])
print(np.linalg.det(m5))

-28.00000000000001
27.999999999999996
27.999999999999996
-56.00000000000002
-167.99999999999997


#### Matrix Inversion

In [222]:
matrix = np.array([ [[1, 2], [9, 4]], [[1, 2], [-8, 1]], [[1, 3], [3, 0]] ])
print(np.linalg.inv(matrix))

[[[-0.28571429  0.14285714]
  [ 0.64285714 -0.07142857]]

 [[ 0.05882353 -0.11764706]
  [ 0.47058824  0.05882353]]

 [[ 0.          0.33333333]
  [ 0.33333333 -0.11111111]]]


##### Orthogonal Matrix

In [235]:
matrix = np.array([[1.0,0.0],[0.,1.]])
comparison = np.dot(matrix.T,matrix) == np.dot(matrix,matrix.T)
print(comparison)
comparison_2 =  np.dot(matrix.T,matrix)== np.eye(2)
print(comparison_2)
comparison_3 = comparison == comparison_2
equal_arrays = comparison_3.all()
print("Is it a orthogonal matrix: ",equal_arrays)

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
Is it a orthogonal matrix:  True


##### Exercise

In [242]:
q = np.array([[0.707168,0.707168,0.],[0.,0.,1],[0.707168,-0.707168,0.]])
q_inv = np.linalg.inv(q)
print(q.T)
print(q_inv)
q.T == q_inv

[[ 0.707168  0.        0.707168]
 [ 0.707168  0.       -0.707168]
 [ 0.        1.        0.      ]]
[[ 0.70704557  0.          0.70704557]
 [ 0.70704557 -0.         -0.70704557]
 [ 0.          1.          0.        ]]


array([[False,  True, False],
       [False,  True, False],
       [ True,  True,  True]])

#### Linear Independence

#### Rank of a Matrix
###### Rank of a matrix A of dimension (m,n) indicates the number of linearly independent columns (or rows) of A.

RankA≤min⁡(m,n)

If Rank(A)=min(m,n) then A is called a full rank matrix. Rank of matrix is always greater than 0 (strictly positive integer)

Rank(A)≥1

In [245]:
matrix = np.array([[1.0,0.0],[0.,1.]])
print(" Rank :",np.linalg.matrix_rank(matrix))
matrix_full_rank = np.eye(4)
print(np.eye(4))
print(" Rank :",np.linalg.matrix_rank(matrix_full_rank))

 Rank : 2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 Rank : 4


### Introduction- Linear Transformation
###### If A is a matrix of dimension (m, n) and x is a vector in n dimension then Ax is a new vector. The vector x is transformed into another vector Ax.

Some examples of such transformation are:

Stretching

Reflection

Rotation

Projection

#### Stretching
###### C.I muttiplied by a matrix or vector streches along the vector or matrix by c where I = Identity matrix

In [267]:
### Below doubtful

matrix = np.array([[1, 5, 9],
              [2, 7, 3],
              [8, 4, 6]])
print("Matrix:",matrix)
print("Streched Matrix:",np.repeat(matrix,3,axis = 1))
np.repeat(matrix,3,axis = 1)

Matrix: [[1 5 9]
 [2 7 3]
 [8 4 6]]
Streched Matrix: [[1 1 1 5 5 5 9 9 9]
 [2 2 2 7 7 7 3 3 3]
 [8 8 8 4 4 4 6 6 6]]


array([[1, 1, 1, 5, 5, 5, 9, 9, 9],
       [2, 2, 2, 7, 7, 7, 3, 3, 3],
       [8, 8, 8, 4, 4, 4, 6, 6, 6]])

In [265]:
matrix = np.array([[1, 5, 9],
              [2, 7, 3],
              [8, 4, 6]])
vector = np.array([1,2,3,4])
print(np.dot(np.identity(4)*3,vector))
print(np.dot(np.identity(3)*3,matrix))

[ 3.  6.  9. 12.]
[[ 3. 15. 27.]
 [ 6. 21.  9.]
 [24. 12. 18.]]


#### Reflection

##### Reflection across x-axis is characterized by the transforming matrix 

a = [[1,0],[0,-1]] which represents (x,-y)

mat.A = reflected image 

##### Reflection across y-axis is characterized by the transforming matrix 

a = [[-1,0],[0,1]] which represents (-x,y)

mat.A = reflected image 

##### Linear Transformation matrix A with columns (0,1) and (1,0) reflect a 2 dimensional object across the line x=y

In [276]:
a = np.array([[1,0],[0,-1]])
mat = np.array([[-1,-2,-3],[1,2,1]])  ### mat is the 3 vertices of the traingle on x-y plane values (x,y)
print(np.dot(a,mat))

[[-1 -2 -3]
 [-1 -2 -1]]


##### Exercise

In [280]:
a = np.array([[0,1],[1,0]])
mat = np.array([[-1,-2,-3],[1,2,1]])
print(np.dot(a,mat))

[[ 1  2  1]
 [-1 -2 -3]]


#### Rotation

Rotation of an object by θ degrees is characterized by matrix

a = [[cos(o) sin(o)],[-sin(o),cos(o)]]

, where θ represents the angle in counter clockwise direction.

If vertices of the triangle are represented as

p = [[-1,-2,-3],[1,2,1]]

, then the rotated triangle is represented as A.P where

a = [[0,1],[-1,0]]

which is (y,-x)

In [282]:
mat = np.array([[-1,-2,-3],[1,2,1]])
a = np.array([[0,1],[-1,0]])
print(np.dot(a,mat))

[[1 2 1]
 [1 2 3]]


In [283]:
matrix = np.array([[1, 2, 9],
              [2, 9, 3],
              [4, 4, 6]])
print("Matrix:",matrix)
print("Rotated Matrix:",np.rot90(matrix))

Matrix: [[1 2 9]
 [2 9 3]
 [4 4 6]]
Rotated Matrix: [[9 3 6]
 [2 9 4]
 [1 2 4]]


#### Projection

Projection of an object along x-axis is characterized by matrix

a = [[1,0],[0,0]]

 i.e. (x,0) and that along y-axis by matrix
 
 a = [[0,0],[0,1]]
 
  i.e. (0,y)

In [284]:
mat = np.array([[-1,-2,-3],[1,2,1]])
a = np.array([[1,0],[0,0]])
print(np.dot(a,mat))

[[-1 -2 -3]
 [ 0  0  0]]


## Linear Equations

In [286]:
Symmetrical_matrix = np.array([[1,2,2],[3,5,3],[-1,4,-1]])
vector=np.array([[4],[19],[7]])
print(Symmetrical_matrix)
print(vector)
print(np.c_[Symmetrical_matrix,vector])
np.c_[Symmetrical_matrix,vector]  ## np.c_ concatenates along the columns and np.r_ concatenates along the rows

[[ 1  2  2]
 [ 3  5  3]
 [-1  4 -1]]
[[ 4]
 [19]
 [ 7]]
[[ 1  2  2  4]
 [ 3  5  3 19]
 [-1  4 -1  7]]


array([[ 1,  2,  2,  4],
       [ 3,  5,  3, 19],
       [-1,  4, -1,  7]])

###### Solving a system of linear equations is equivalent to finding where the set of planes represented by linear equations meet. For the matrix A, if m=n and A is a full rank matrix, then there exists a unique solution for linear equations.

In the previous example,which is of the form Ax=b

It is observed that A ha dimension (3,3) i.e. m=3 and n=3, and that the rank of A is 3.

Therefore, he set of linear equations represented by A has a unique solution.

This can be solved in python using

##### A system of n linear equations with n variables has unique solution if

##### 1. Coefficient matrix is full rank
##### 2. Determinant of coefficient materix is non-zero

In [295]:
mat1 = np.array([[1, 3, -1],
              [2, 5, 4],
              [2, 3, -1]])

mat2 = np.array([4,19,7])
print("Rank of the matrix is :",np.linalg.matrix_rank(mat2))
# print(matrix_2.shape)
x= np.linalg.solve(mat1, mat2)
print("Set of Planes",x)

Rank of the matrix is : 1
Set of Planes [3. 1. 2.]


It will be useful to investigate how to solve a system of Linear equations assuming m=n (i.e. square matrix) and all columns (or rows) are linearly independent.

Two commonly used techniques to solve a system of Linear equations are:

### 1. Gaussian Elimination

### 2. Cramer’s Rule

If Ax=b, and A is of dimension (m,n) that is A is not a square matrix.

If m < n (A is fat matrix) the system is called under-determined system

If m > n (A is thin/tall matrix) the system is called over-determined system.

Given Ax=b , if A is invertible (inverse exists) then the solution is,

x=(A-1)b  # a inverse

Only problem is we need to find inverse of a non-square matrix which can be found using generalized inverse

x=(A-G)b  # a inverse 

Where A-G represents generalized inverse (also called pseudo inverse)

In [303]:
matrix_a = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
              [1, 1, 1]])
matrix_b = np.array([[1],[2],[3],[6]])
matrix_inv_a = np.linalg.pinv(matrix_a)
print("Generalized Inverse :", np.linalg.pinv(matrix_a))

print(np.matmul(matrix_inv_a,matrix_b))

#print(np.linalg.solve(matrix_a,matrix_b))  #wont work beacuse solve is for square matrix

Generalized Inverse : [[ 0.75 -0.25 -0.25  0.25]
 [-0.25  0.75 -0.25  0.25]
 [-0.25 -0.25  0.75  0.25]]
[[1.]
 [2.]
 [3.]]


## Eigen Values and Eigen Vectors

An eigenvector is a vector in a system that does not change its direction under associated linear transformation.

For example, consider a globe which can be rotated about an axis (in case of Earth the poles are the axis about which it is rotated). When the globe is rotated all points on the surface get changed (linearly transformed) except the point that represent the poles, i.e. the direction of axis is not changing. This is called the eigen vector of the globe.

During the linear transformation, the eigen vectors may get scaled. The factor by which the vector gets scaled is called as the eigen value of the vector. If an eigen value associated with an eigen vector is smaller than 1 then all vectors in the direction of this eigen vector will shrink when transformed. If the eigen value is 1 then no change in size and if eigen value is greater than 1 then vectors expand.

Eigen values and vectors are used in many computations for applications such as stability analysis and physics of rotating bodies. Google’s Page rank algorithm also uses eigen vectors. Here these eigen vectors represent page rank values.

#### When A is symmetric, the Eigen vectors corresponding to different Eigen values are orthogonal.
#### Sum of Eigen values of A is trace of matrix A where trace of A is sum of diagonal values of A

In [334]:
A = np.array([[1,0],[0,-2]])
#print(A)
results = np.linalg.eig(A)
print(results)
'''Eigen Values and Eigen Vectors are present as a tuple in results'''
'''Separating Eigen Values and Eigen Vectors'''
eigvals, eigvecs = np.linalg.eig(A)
print("Eigen Values :",eigvals)
print("Eigen Vectors :",eigvecs)

(array([ 1., -2.]), array([[1., 0.],
       [0., 1.]]))
Eigen Values : [ 1. -2.]
Eigen Vectors : [[1. 0.]
 [0. 1.]]


#### Exercise

In [332]:
a = np.array([[2,0],[0,1]])
print("Rank of the matrix is :",np.linalg.matrix_rank(a))
results = np.linalg.eig(a)
print("Eigen values :",results[0])
print("Eigen vector :",results[1])

Rank of the matrix is : 2
Eigen values : [2. 1.]
Eigen vector : [[1. 0.]
 [0. 1.]]


#### Diagonal Form

In [330]:
array = np.array([[1,4,7],[2,5,8],[3,6,9]])
print("Array:",array)
eigenvalues, eigenvectors = np.linalg.eig(array)
print ("eigenvalues :",np.round(eigenvalues))
print ("eigenvectors :",eigenvectors)
inverseEigenVectors = np.linalg.inv(eigenvectors) 
diagonal= np.round(np.dot(np.dot(inverseEigenVectors,array),eigenvectors))
print("diagonal form",diagonal)

Array: [[1 4 7]
 [2 5 8]
 [3 6 9]]
eigenvalues : [16. -1. -0.]
eigenvectors : [[-0.46454727 -0.88290596  0.40824829]
 [-0.57079553 -0.23952042 -0.81649658]
 [-0.67704379  0.40386512  0.40824829]]
diagonal form [[16. -0.  0.]
 [ 0. -1. -0.]
 [ 0. -0. -0.]]


#### Positive Definite Matrix
##### Positive Definite: Matrix of dimension (n,n)  is said to be Positive Definite if all Eigen values are positive
##### Positive Semi-Definite: If all Eigen values of matrix A are non-negative then matrix A is said to Positive-Semi-Definite

In [335]:
array = np.array([[1,4,7],[2,5,8],[3,6,9]])
eigenvalues, eigenvectors = np.linalg.eig(array)
print("eigenvalues",eigenvalues)
array_2 = np.array([[9.847914,10.38333,49.88812],[10.38333,40.600000,62.66000],[49.888118,62.66000,270.20280]])
eigenvalues, eigenvectors = np.linalg.eig(array_2)
print("eigenvalues",eigenvalues)

eigenvalues [ 1.61168440e+01 -1.11684397e+00 -1.57673427e-16]
eigenvalues [295.26997368   0.5603803   24.82036002]


## Introduction- Matrix Decomposition
A given matrix can be factorized into matrices for various reasons such as simplifying computations e.g. solving system of linear equations, finding new basis (vectors spanning a subspace) etc.

There are different matrix decomposition techniques based on purpose, structure of matrix etc. that can be used to factorize a given matrix. Some of these matrix decomposition techniques are:

LU decomposition

QR decomposition

Cholesky decomposition

Spectral decomposition

Singular Value Decomposition (SVD)

##### LU Decomposition

In [345]:
import scipy.linalg
A = scipy.array([[1, 2, 3],
[4, 5, 6],
[10, 11, 9]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.1        1.         0.        ]
 [0.4        0.66666667 1.        ]]
[[10.  11.   9. ]
 [ 0.   0.9  2.1]
 [ 0.   0.   1. ]]


C:\Users\malla\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  after removing the cwd from sys.path.


#### QR Decomposition

QR decomposition is predominantly used for solving linear least square problem which is one of the widely used technique in scientific computation including fitting function for given data, in a numerically stable fashion, QR decomposition can also be used to find Eigen values and Eigen vectors and solving system of linear equations which are not square.

In [346]:
matrix_1 = np.array([[1,3,-1],[2,5,4],[2,3,-1]])
print("A",matrix_1)
matrix_2 = np.array([4, 19, 7])
print("B",matrix_2)
q, r = np.linalg.qr(matrix_1)
p = np.dot(q.T, matrix_2)
print("QR Decomposition",np.dot(np.linalg.inv(r), p))

A [[ 1  3 -1]
 [ 2  5  4]
 [ 2  3 -1]]
B [ 4 19  7]
QR Decomposition [3. 1. 2.]


#### Cholesky Decomposition
Diagonal values of L are positive. This is applicable for positive definite matrices.

In [350]:
matrix_1 = np.array([[9.847914,10.38333,49.88812],[10.383333,40.60000,62.66000],[49.888118,62.66000,270.20280]])
H = np.linalg.cholesky(matrix_1)
print("H :",H.transpose())
print("Cholesky Decomposition :",np.dot(L, L.T.conj())) # verify that L * L.H = A

H : [[ 3.13813862  3.30875537 15.89735956]
 [ 0.          5.44537767  1.84735143]
 [ 0.          0.          3.75020688]]
Cholesky Decomposition : [[1.         0.1        0.4       ]
 [0.1        1.01       0.70666667]
 [0.4        0.70666667 1.60444444]]


#### Singular Value Decomposition

Matrix A of dimension (m,n) can be decomposed into three matrices as



Where D is a diagonal matrix having non-negative values, U and V are orthogonal matrices.

Diagonal values of D are called Singular Values of matrix A. One of the remarkable property of SVD decomposition is that matrix A can be Singular.

Some of the important applications of SVD are

Inverting non-square or singular matrix (called Generalized inverse or Pseudo-inverse) 

Low Rank approximation

Regression Analysis

SVD is closely related to Principal Component Analysis (PCA) which is widely used in dimensionally reduction.

Python command svd can be used to achieve singular value decomposition of a matrix.

In [358]:
array = np.array([[1,3,-1],[2,5,4],[2,3,-1]])
print("A:",array)
u, d, v = np.linalg.svd(array)
print("U:",u)
print("D:",d)
print("V:",v)

A: [[ 1  3 -1]
 [ 2  5  4]
 [ 2  3 -1]]
U: [[-0.34272777  0.57075334 -0.74617578]
 [-0.85357667 -0.5209279  -0.00640185]
 [-0.39235767  0.63472415  0.6657182 ]]
D: [7.55742687 3.53268255 0.63675206]
V: [[-0.37507428 -0.85652694 -0.35451501]
 [ 0.22598856  0.28640925 -0.93107407]
 [ 0.89902639 -0.42933827  0.08614054]]


In [359]:
array = np.array([[1,3,-1],[2,5,4]])
print("A:",array)
u, d, v = np.linalg.svd(array)
print("U:",u)
print("D:",d)
print("V:",v)

eigvalues,eigvectors = np.linalg.eig(np.dot(array,array.T))
print("Values :",eigvalues)
print("Vectors :",eigvectors)

A: [[ 1  3 -1]
 [ 2  5  4]]
U: [[-0.32065727 -0.94719529]
 [-0.94719529  0.32065727]]
D: [7.02857984 2.56886462]
V: [[-0.31514871 -0.81068272 -0.49343167]
 [-0.11907235 -0.48204157  0.86801941]
 [ 0.94154292 -0.33230927 -0.05538488]]
Values : [ 6.59906544 49.40093456]
Vectors : [[-0.94719529 -0.32065727]
 [ 0.32065727 -0.94719529]]
